### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by wmluke** [dstockman/puppet-stackdriver-agent#23]
Hi @dstockman,

Can you cut a new release so we can include the most recent `puppet-stackdriver-agent` by  a tagged version?  Specifically, if we use `:ref => 'master'`, then we might accidentally pull in breaking changes.

**Comment by dstockman** [comment]
Hey @wmluke! Do you mind using the Puppet forge for now (https://forge.puppetlabs.com/dstockman/stackdriver)? I have some changes in the mix and will hook up a new release in the near future. Version 1.2.0 is cut there.. Thanks!

**Comment by coreone** [comment]
+1 on this...would really like to start using the new zookeeper plugin if possible without needing to use the GitHub repo URL in R10k!

Thanks!

**Comment by dstockman** [comment]
I cut a release here and on the puppetforge, too: https://forge.puppetlabs.com/dstockman/stackdriver/
