### ISSUE TITLE
module install fails

### ISSUE THREAD

**Issue by fluzz** [dstockman/puppet-stackdriver-agent#28]
when installing the module on a fedora instance with puppet 4.1.0 using 
```
puppet apply -e "class { 'stackdriver': apikey => 'OMGBECKYLOOKATHERBUTTITSJUSTSOBIG', }"
```

returns the error
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class ::stackdriver::install::RedHat at /home/vagrant/modules/stackdriver/manifests/init.pp:51:3 on node localhost
```

I'm guessing this is caused by puppet 4.0 

full debug log https://gist.github.com/fluzz/28caa1bd34690b323d3b

**Comment by dstockman** [comment]
Thanks for the report! I haven't started on the 4.0 train yet and don't have the cycles at the moment to work on testing this against the new parser. If you feel up to it, I'd welcome a PR. :) Thanks again!
