### ISSUE TITLE
incompatibility with PE 2015.2 ? 

### ISSUE THREAD

**Issue by leshiynyc** [dstockman/puppet-stackdriver-agent#31]
Hi, 

Trying to use your module with PE 2015.2 and getting the following error: 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class ::stackdriver::install::RedHat at /etc/puppetlabs/puppet/environments/production/modules/stackdriver/manifests/init.pp:51:3 on node

This works fine on PE 3.8.x 

Notice "::stackdriver::install::RedHat",  where it is looking for ::stackdriver::install::redhat

**Comment by dstockman** [comment]
Thanks for the report! 

I haven't tested with PE and don't have that setup here so I can't really help too much. I welcome a pull request with a fix if you're up for it!

**Comment by leshiynyc** [comment]
As soon as I know how to fix this.

**Comment by leshiynyc** [comment]
this does the trick 
in init.pp

    $iclass = downcase("${name}::install::${::osfamily}")
    $cclass = downcase("${name}::config::${::osfamily}")

**Comment by dstockman** [comment]
Do you mind to hook this up in a pull request? Thanks!

**Comment by bsdfirst** [comment]
I have not tested in PE; however, I have just created a PR for Puppet 4.x compatibility that should also resolve this issue.

**Comment by dstockman** [comment]
Merged PR @bsdfirst mentioned. Thanks everyone!
